//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revelante
    {
        public int Id_Revelante { get; set; }
        public string Descripcion { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<int> Id_Vigilante { get; set; }
        public string Hora { get; set; }
        public string Fecha { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Vigilante Vigilante { get; set; }
    }
}
