//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vigilante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vigilante()
        {
            this.Control_Visitante_Ocurrencias = new HashSet<Control_Visitante_Ocurrencias>();
            this.Revelante = new HashSet<Revelante>();
        }
    
        public int Id_Vigilante { get; set; }
        public string Nombre { get; set; }
        public string Dni { get; set; }
        public string Turno { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> idusuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Control_Visitante_Ocurrencias> Control_Visitante_Ocurrencias { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revelante> Revelante { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
